# -*- coding: utf-8 -*-
"""final pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGFjVW6eOcqOFKrS8SoLJi3qpbl7zn8e
"""

# Importing necessary libraries
import os
import zipfile
import requests
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator

!pip install torch torchvision
!pip install opencv-python pillow matplotlib



# Importing required libraries
import tensorflow as tf
from tensorflow.keras.datasets import cifar10  # Example: CIFAR-10 dataset
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import matplotlib.pyplot as plt

# Load the CIFAR-10 dataset (this dataset is already available in TensorFlow)
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Show the shape of the dataset
print(f'Training data shape: {x_train.shape}')
print(f'Testing data shape: {x_test.shape}')

# Normalize the data (scaling pixel values to be between 0 and 1)
x_train, x_test = x_train / 255.0, x_test / 255.0

# Convert labels to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# Plotting a few images from the CIFAR-10 dataset
plt.figure(figsize=(10, 10))
for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(x_train[i])
    plt.title(f'Label: {y_train[i].argmax()}')
    plt.axis('off')
plt.show()

# Build the CNN model
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')  # 10 classes in CIFAR-10
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train, epochs=10, batch_size=64, validation_data=(x_test, y_test))

# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f"Test accuracy: {test_acc * 100:.2f}%")

# Import a pre-trained model (e.g., ResNet50)
from tensorflow.keras.applications import ResNet50

# Load the pre-trained model (with weights from ImageNet)
model = ResNet50(weights='imagenet')

# Display the model summary
model.summary()

# Example: Downloading a dataset using wget
!wget https://example.com/your-dataset.zip  # Replace with the actual URL

# Unzip the downloaded dataset
!unzip your-dataset.zip -d dataset/

# Import TensorFlow Datasets
import tensorflow_datasets as tfds

# Load the CIFAR-10 dataset from TensorFlow Datasets
dataset, info = tfds.load('cifar10', with_info=True)

# Display dataset information
print(info)

# Extract training and testing sets
train_data, test_data = dataset['train'], dataset['test']

# Importing required libraries
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import cifar10

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the data (scaling pixel values to be between 0 and 1)
x_train, x_test = x_train / 255.0, x_test / 255.0

# Convert labels to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)
# Build the CNN model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')  # 10 classes in CIFAR-10
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(x_train, y_train, epochs=10, batch_size=64, validation_data=(x_test, y_test))
# Plotting Accuracy
plt.figure(figsize=(12, 6))

# Training and Validation Accuracy Plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Training and Validation Loss Plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

# Display the plots
plt.tight_layout()
plt.show()

import tensorflow as tf
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import torch
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)  # Using the small YOLOv5 model

# Function to Capture Image from Webcam
def capture_image():
    # JavaScript code to capture webcam feed
    js = """
    async function takePhoto() {
        const div = document.createElement('div');
        const capture = document.createElement('button');
        capture.textContent = 'Capture';
        div.appendChild(capture);
        document.body.appendChild(div);

        const video = document.createElement('video');
        div.appendChild(video);

        const stream = await navigator.mediaDevices.getUserMedia({ video: true });

        video.srcObject = stream;
        await video.play();

        // Wait for user to press Capture button
        await new Promise((resolve) => capture.onclick = resolve);

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        stream.getTracks().forEach(track => track.stop());
        div.remove();

        return canvas.toDataURL('image/jpeg');
    }
    takePhoto();
    """
    display(Javascript(js))
    data = eval_js('takePhoto()')
    image_bytes = b64decode(data.split(',')[1])
    img_array = np.frombuffer(image_bytes, dtype=np.uint8)
    return cv2.imdecode(img_array, cv2.IMREAD_COLOR)

# Capture an image from the webcam
image = capture_image()

# Perform object detection using YOLOv5
results = model(image)

# Display detection results
results.show()

import torch
import cv2
import numpy as np
from base64 import b64decode
from IPython.display import display, Javascript
from google.colab.output import eval_js

# Load model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)

def capture_image():
    js = """
    async function takePhoto() {
        const video = document.createElement('video');
        const stream = await navigator.mediaDevices.getUserMedia({video: true});
        document.body.appendChild(video);
        video.srcObject = stream;
        await video.play();

        await new Promise(resolve => setTimeout(resolve, 3000));

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        stream.getTracks().forEach(track => track.stop());
        video.remove();

        return canvas.toDataURL('image/jpeg');
    }
    """
    display(Javascript(js))
    data = eval_js("takePhoto()")
    binary = b64decode(data.split(',')[1])
    image = np.frombuffer(binary, dtype=np.uint8)
    return cv2.imdecode(image, cv2.IMREAD_COLOR)

# Capture image
image = capture_image()

# Convert BGR → RGB
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Detection
results = model(image)

# Show result
results.show()

# Importing required libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from tensorflow.keras.datasets import cifar10
import tensorflow as tf

# Load the CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Normalize the data (scaling pixel values to be between 0 and 1)
x_train, x_test = x_train / 255.0, x_test / 255.0

# Flatten the images for the SVM model
x_train_svm = x_train.reshape(x_train.shape[0], -1)
x_test_svm = x_test.reshape(x_test.shape[0], -1)

# Standardize the data (SVM works better with standardized data)
scaler = StandardScaler()
x_train_svm = scaler.fit_transform(x_train_svm)
x_test_svm = scaler.transform(x_test_svm)

# Apply PCA for dimensionality reduction (SVM may struggle with high-dimensional data)
pca = PCA(n_components=500)  # Reduce to 500 components for faster training
x_train_svm = pca.fit_transform(x_train_svm)
x_test_svm = pca.transform(x_test_svm)

svm_accuracy = 42.78  # Assume a hypothetical accuracy
cnn_accuracy = 86.45  # Replace with your CNN's actual accuracy

# Plot comparison
import matplotlib.pyplot as plt

models = ['SVM', 'CNN']
accuracies = [svm_accuracy, cnn_accuracy]

plt.bar(models, accuracies, color=['blue', 'green'])
plt.title('Accuracy Comparison')
plt.ylabel('Accuracy (%)')
plt.show()

import numpy as np
from sklearn import svm
from sklearn.metrics import accuracy_score
from tensorflow.keras.datasets import cifar10
from sklearn.preprocessing import StandardScaler

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Flatten the image data for SVM (from 32x32x3 to 3072)
x_train_flat = x_train.reshape(x_train.shape[0], -1)
x_test_flat = x_test.reshape(x_test.shape[0], -1)

# Scale the data to have zero mean and unit variance
scaler = StandardScaler()
x_train_flat = scaler.fit_transform(x_train_flat)
x_test_flat = scaler.transform(x_test_flat)

# Convert labels to 1D array
y_train = y_train.ravel()
y_test = y_test.ravel()

pip install opencv-python tensorflow keras

pip install ultralytics

!wget https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5s.pt

# Commented out IPython magic to ensure Python compatibility.
!pip install opencv-python-headless
!pip install torch torchvision pandas matplotlib
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np

def capture_image():
    # JavaScript code to capture webcam feed
    js = """
    async function takePhoto() {
        const div = document.createElement('div');
        const capture = document.createElement('button');
        capture.textContent = 'Capture';
        div.appendChild(capture);
        document.body.appendChild(div);

        const video = document.createElement('video');
        div.appendChild(video);

        const stream = await navigator.mediaDevices.getUserMedia({ video: true });

        video.srcObject = stream;
        await video.play();

        // Wait for user to press Capture button
        await new Promise((resolve) => capture.onclick = resolve);

        const canvas = document.createElement('canvas');
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);

        stream.getTracks().forEach(track => track.stop());
        div.remove();

        return canvas.toDataURL('image/jpeg');
    }
    takePhoto();
    """
    display(Javascript(js))
    data = eval_js('takePhoto()')
    image_bytes = b64decode(data.split(',')[1])
    img_array = np.frombuffer(image_bytes, dtype=np.uint8)
    return cv2.imdecode(img_array, cv2.IMREAD_COLOR)

import torch

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s', pretrained=True)  # Using the small YOLOv5 model

# Capture an image from the webcam
image = capture_image()

# Perform object detection using YOLOv5
results = model(image)

# Display detection results
results.show()  # Display the image with bounding boxes

